FORMAT: 1A
HOST: http://findgamesfor.me/api

# GamesObservatory

The Games Observatory API uses a RESTful interface to retrieve data about video
games, including game information, company information, and a timeline.

## All Games [/games]
### Get All Games [GET]

+ Response 200 (application/json)

        [
  {
    " Game": "Thief II: The Metal Age",
    "Companies": [
      "Eidos Interactive",
      "Square Enix",
      "Looking Glass Studios"
    ],
    "Genres": [
      "Shooter"
    ],
    "Platforms": [
      "Microsoft Windows"
    ],
    "Rating": 9.13,
    "Year": 2000,
    "game_id": 1
  },
  {
    " Game": "Thief: The Dark Project",
    "Companies": [
      "Looking Glass Studios",
      "Eidos Interactive",
      "Square Enix"
    ],
    "Genres": [
      "Shooter"
    ],
    "Platforms": [
      "Microsoft Windows"
    ],
    "Rating": 8.39,
    "Year": 1998,
    "game_id": 2
  },
  {
    " Game": "Thief: Deadly Shadows",
    "Companies": [
      "Ion Storm",
      "Eidos Interactive",
      "Square Enix"
    ],
    "Genres": [
      "Shooter"
    ],
    "Platforms": [
      "Microsoft Windows",
      "Xbox"
    ],
    "Rating": 8.04,
    "Year": 2004,
    "game_id": 3
  }
]

## Single Game [/games/{id}]
### Get A Specific Game [GET]
+ Parameters
    + id (required, int) ... ID of the game 
    
+ Response 200 (application/json)

        [
  {
    "companies_to_url": [
      {
        "name": "Eidos Interactive",
        "url": "/companies/4"
      },
      {
        "name": "Square Enix",
        "url": "/companies/26"
      },
      {
        "name": "Looking Glass Studios",
        "url": "/companies/3"
      }
    ],
    "game_id": 1,
    "genres": [
      "Shooter"
    ],
    "image_url": "https://res.cloudinary.com/igdb/image/upload/t_cover_small/qagoforxr6tofvpmgy9g.png",
    "name": "Thief II: The Metal Age",
    "platforms": [
      "Microsoft Windows"
    ],
    "rating": 9.13,
    "year": 2000
  }
]
        
## All Companies [/companies]

### Get All Companies [GET]

+ Response 200 (application/json)

        [
  {
    " Company": "Electronic Arts",
    "Average Rating": 7.79,
    "Number of Games Developed": 0,
    "Number of Games Published": 11,
    "Year Founded": 1982,
    "company_id": 1
  },
  {
    " Company": "BioWare",
    "Average Rating": 8.6,
    "Number of Games Developed": 6,
    "Number of Games Published": 0,
    "Year Founded": 1995,
    "company_id": 2
  }
]

## Single Company [/companies/{id}]
### Get A Specific Company [GET]
+ Parameters
    + id (required, int) ... ID of the game 
    
+ Response 200 (application/json)

        [
  {
    "avg_rating": 8.6,
    "company_id": 2,
    "games_to_url": [
      {
        "name": "Baldur's Gate",
        "url": "/games/5"
      },
      {
        "name": "Baldur's Gate II: Shadows Of Amn",
        "url": "/games/6"
      },
      {
        "name": "Jade Empire: Special Edition",
        "url": "/games/10"
      },
      {
        "name": "Mass Effect",
        "url": "/games/73"
      },
      {
        "name": "Mass Effect 2",
        "url": "/games/74"
      },
      {
        "name": "Mass Effect 3",
        "url": "/games/75"
      }
    ],
    "image_url": "https://res.cloudinary.com/igdb/image/upload/t_thumb/kxhml6iozkzgm2ewt0lo.png",
    "name": "BioWare",
    "num_developed": 6,
    "num_published": 0,
    "year": 1995
  }
]


## All years [/years]
### Get Game statistics From all years [GET]

+ Response 200 (application/json)
        
        [
  {
    " Year": 1955,
    "Average Rating": null,
    "Most popular genre": null,
    "Number of Companies Founded": 1,
    "Number of Games": 0
  },
  {
    " Year": 1979,
    "Average Rating": null,
    "Most popular genre": null,
    "Number of Companies Founded": 2,
    "Number of Games": 0
  },
  {
    " Year": 1980,
    "Average Rating": null,
    "Most popular genre": null,
    "Number of Companies Founded": 1,
    "Number of Games": 0
  },
  {
    " Year": 1982,
    "Average Rating": null,
    "Most popular genre": null,
    "Number of Companies Founded": 4,
    "Number of Games": 0
  },
  {
    " Year": 1983,
    "Average Rating": null,
    "Most popular genre": null,
    "Number of Companies Founded": 2,
    "Number of Games": 0
  },
  {
    " Year": 1984,
    "Average Rating": null,
    "Most popular genre": null,
    "Number of Companies Founded": 1,
    "Number of Games": 0
  }
]
    
## Specified year [/years/{year}]
### Get Game statistics From A Specific Time Period [GET]

+ Parameters
    + year (required, int) ... Year to get

+ Response 200 (application/json)
        
        [
  {
    "avg_rating": 8.96,
    "companies_to_url": [
      {
        "name": "Looking Glass Studios",
        "url": "/companies/3"
      },
      {
        "name": "Eidos Interactive",
        "url": "/companies/4"
      }
    ],
    "games_to_url": [
      {
        "name": "The Secret of Monkey Island",
        "url": "/games/60"
      }
    ],
    "most_popular_genre": "Adventure",
    "num_games": 1,
    "year_id": 1990
  }
]