version: "2"

# A Docker Compose file for configuration of the production environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    image: wripley/pythonwebapp_lb
    environment:
      # Always deploy to n1 so the lb always has the same IP address. This is
      # just for convenience and isn't strictly necessary.
      - "constraint:node==*n1"

  app:
    extends:
      file: docker-compose-common.yml
      service: app
    image: wripley/pythonwebapp_app
    expose:
      # Expose port 8000 so it's only visibile on the container, not the host
      - "8000"
    env_file: pythonwebapp-postgres-prod.env
    command: gunicorn app:app --bind 0.0.0.0:8000
      # Run Gunicorn to serve app requests

  db:
    extends:
      file: docker-compose-common.yml
      service: db
    image: wripley/pythonwebapp_db
    expose:
      # Expose port 5432 so it's only visibile on the container, not the host
      - "5432"
    env_file:
      - pythonwebapp-postgres-prod.env
      # - pythonwebapp-postgres-root-prod.env
    volumes_from:
      # Mount the volumes from the data container to store our MySQL files
      - data

  data:
    extends:
      file: docker-compose-common.yml
      service: data

networks:
  backend: {}
